FROM golang:1.24-alpine AS build

WORKDIR /app
COPY app/go.mod app/go.sum ./
RUN go mod download
COPY app/ ./
RUN CGO_ENABLED=0 GOOS=linux go build -o backend

FROM alpine:latest

WORKDIR /
COPY --from=build /app/backend backend
EXPOSE 8080

ENTRYPOINT ["/backend"]
