services:
  db:
      image: postgres:17.5
      volumes:
        - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh
        - postgres:/var/lib/postgresql/data/pgdata
        - ./configs/postgresql.conf:/etc/postgresql/postgresql.conf
        - ./configs/pg_hba.conf:/etc/postgresql/pg_hba.conf
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - PGDATA=/var/lib/postgresql/data/pgdata
        - DB_NAME
        - DB_USER
        - DB_PASSWORD
      command: ["--config_file=/etc/postgresql/postgresql.conf", "--hba_file=/etc/postgresql/pg_hba.conf"]
      healthcheck:
        test:
          [
            "CMD-SHELL",
            "pg_isready --username=${DB_USER} --port=${POSTGRES_PORT} --dbname=${DB_NAME}",
          ]
        start_period: 2s
        interval: 5s
        timeout: 5s
        retries: 5
      restart: unless-stopped
volumes:
  postgres: