!/bin/bash
set -e
PGPASSWORD="$POSTGRES_PASSWORD" psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "postgres" <<-EOSQL
    CREATE USER ${DB_USER} WITH ENCRYPTED PASSWORD '${DB_PASSWORD}';
    ALTER USER ${DB_USER} CREATEDB;
EOSQL
PGPASSWORD="$DB_PASSWORD" psql -v ON_ERROR_STOP=1 --username "$DB_USER" -d "postgres" <<-EOSQL
    CREATE DATABASE ${DB_NAME};
EOSQL
