name: frontend

on:
  push:
    branches:
      - feat/koyeb

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: ./devops/Dockerfile.prod.frontend
          push: true
          tags: tibo43/calciotto-frontend:latest
  koyeb:
    runs-on: ubuntu-latest
    needs:
      - docker
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"

      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: calciotto
          service-name: frontend
          service-type: web
          service-instance-type: free
          service-regions: fra
          service-ports: "3000:http"
          service-routes: "/:3000"
          docker: tibo43/calciotto-frontend:latest